/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zuochengyao_sdk_engine_ZcyNative */

#ifndef _Included_com_zuochengyao_sdk_engine_ZcyNative
#define _Included_com_zuochengyao_sdk_engine_ZcyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zuochengyao_sdk_engine_ZcyNative
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zuochengyao_sdk_engine_ZcyNative_helloWorld
  (JNIEnv *, jclass);

/*
 * Class:     com_zuochengyao_sdk_engine_ZcyNative
 * Method:    updateFileContent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zuochengyao_sdk_engine_ZcyNative_updateFileContent
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
