/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zcy_sdk_engine_JniNative */

#ifndef _Included_com_zcy_sdk_engine_JniNative
#define _Included_com_zcy_sdk_engine_JniNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zcy_sdk_engine_JniNative
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zcy_sdk_engine_JniNative_helloWorld
  (JNIEnv *, jclass);

/*
 * Class:     com_zcy_sdk_engine_JniNative
 * Method:    updateFileContent
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zcy_sdk_engine_JniNative_updateFileContent
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
