package com.icheero.sdk.core.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.icheero.sdk.core.database.entity.User;
import com.icheero.sdk.core.database.entity.Download;

import com.icheero.sdk.core.database.greendao.UserDao;
import com.icheero.sdk.core.database.greendao.DownloadDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig downloadDaoConfig;

    private final UserDao userDao;
    private final DownloadDao downloadDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        downloadDaoConfig = daoConfigMap.get(DownloadDao.class).clone();
        downloadDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        downloadDao = new DownloadDao(downloadDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Download.class, downloadDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        downloadDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public DownloadDao getDownloadDao() {
        return downloadDao;
    }

}
