package com.icheero.sdk.core.storage.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.icheero.sdk.core.storage.database.entity.Download;
import com.icheero.sdk.core.storage.database.entity.User;

import com.icheero.sdk.core.storage.database.greendao.DownloadDao;
import com.icheero.sdk.core.storage.database.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadDaoConfig;
    private final DaoConfig userDaoConfig;

    private final DownloadDao downloadDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadDaoConfig = daoConfigMap.get(DownloadDao.class).clone();
        downloadDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        downloadDao = new DownloadDao(downloadDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Download.class, downloadDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        downloadDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public DownloadDao getDownloadDao() {
        return downloadDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
